#!/bin/bash
ARGUMENTS="$@"
BRANCH="main"
DRYRUN="0"
GITPARAMS=()
RELEASEDATE=$(date '+%Y%m%d')
RELEASENOTES=""
REMOTE="origin"
PREVIOUS_COMMIT=""
RUNSILENT="0"
VERBOSE="0"
VERSIONTYPE="patch"
LATEST_RELEASE=$(git tag | sort -V | tail -1)

SECONDS=0
# do some work
echo BASH GIT TOOLS $LATEST_RELEASE

echo

# Here you execute your script from function in external file
source ./utils/spinner.sh
source ./tag-update.sh
spinnerExport

echo 

tagUpdate

echo

duration=$SECONDS
echo "Everything completed in $(($duration / 60)) minutes and $(($duration % 60)) seconds."